### ISSUE TITLE
Will someone please explain this to me?

### ISSUE THREAD

**Issue by thewhiterabbit** [tronprotocol/tron-box#104]
Tron-box is not using the version of solidity compiler I have installed. Why?
![Screenshot_2019-05-07_08-04-24](https://user-images.githubusercontent.com/5334222/57311712-06583380-70a1-11e9-8be7-756873305509.png)
![Screenshot_2019-05-07_08-25-33](https://user-images.githubusercontent.com/5334222/57312093-bd54af00-70a1-11e9-9be3-34ba17ac8c73.png)

UPDATE: I see that the Solidity version is explicitly set in `/packages/tron-solc/package.json`.
Will changing this to 0.5.8 actually change the compiler version, or no?

I have tried RTFM, to no avail...
![Screenshot_2019-05-07_10-28-58](https://user-images.githubusercontent.com/5334222/57320131-0a8d4c80-70b3-11e9-9317-a7971b32fb72.png)

UPDATE: Pull request submitted.
If I have made an error in my thinking please tell me. I want to help. Can we add a command that will use the specified version like: `tronbox compile --version 0.5.8`?

**Comment by sullof** [comment]
Tron is not compatible with solcjs.
TronBox uses a modified version of solc that is able to handle trc10 token, multisignatures, etc. and is fully compatible with the Tron TVM. Don't try to force it because, even if you can deploy a contract compiled with a different compiler, the execution of the contract itself can bring unpredictable (potentially unsafe) results.
