### ISSUE TITLE
Error: ContractTwo has not been deployed to detected network

### ISSUE THREAD

**Issue by fyang1024** [tronprotocol/tron-box#29]
ContractTwo is deployed after ContractOne is deployed in my migration script. My ContractOne.test.js passes, but ContractTwo.test.js sometimes pass and sometimes not. See [my repo](https://github.com/fyang1024/tronbox-testbed.git)
<img width="708" alt="screen shot 2018-12-04 at 12 21 55 am" src="https://user-images.githubusercontent.com/20808865/49376355-0e5f2080-f75b-11e8-9490-3c2164c6553f.png">

**Comment by sullof** [comment]
There was a critical error in the previous version. 
We just published TronBox 2.0.1, which supports the new java-tron 3.2 and fixes a couple of issues. Can you update and try again, please?
```
npm update -g tronbox
```

**Comment by sullof** [comment]
_(I removed my previous response because it was not useful)_

I cloned your repo and ran migration and testing. I used Tron Quickstart 1.2.3 and TronBox 2.2.1.

Both worked well, except the third one, where you use 
```
contractThree = await ContractThree.new();
```
because `artifact.new()` is not supported right now by TronBox.
Also, I created a script and ran the tests, with an interval of 20 seconds, 100 times and all the times the second test passed. I guess there was an issue in the previous versions of TronBox/Tron Quickstart.

**Comment by fyang1024** [comment]
> _(I removed my previous response because it was not useful)_
> 
> I cloned your repo and ran migration and testing. I used Tron Quickstart 1.2.3 and TronBox 2.2.1.
> 
> Both worked well, except the third one, where you use
> 
> ```
> contractThree = await ContractThree.new();
> ```
> because `artifact.new()` is not supported right now by TronBox.
> Also, I created a script and ran the tests, with an interval of 20 seconds, 100 times and all the times the second test passed. I guess there was an issue in the previous versions of TronBox/Tron Quickstart.

I upgraded both tronbox and tron docker image, now they are working as expected.
Great job! Thanks
