### ISSUE TITLE
can't change the account to deploy from

### ISSUE THREAD

**Issue by infine8** [tronprotocol/tron-box#64]
hi,

I managed to deploy my contract to Shasta network, but Tronbox deployed it from unknown account. When I saw contract's creator address, it wasn't what I expected to see. I thought It was going to deploy from the account which private key I put in tronbox.js, but it wasn't. So, why does tronbox need a private key in its config file? How to change deployer's address? Tried to add a field "from" in the config. It didn't work

**Comment by sullof** [comment]
TronBox uses the settings, giving priority to settings inside `migrations/2_deploy_contracts.js` if there.
The from field is ignored because the default address is taken from the private ley. Without a private key the migration can only fail. There is no magic there, you are setting a private key somehow.
I suppose you used `tronWeb.address.fromPrivateKey(your_pk)` to get the creator address.
Can you give me the address of the deployed contract, please, so that I can investigate?
Thanks.

**Comment by infine8** [comment]
here it is
    (base58) TBjSkAjXwDuQj8afcPJnYViq6G3izvY3Jw
    (hex) 411355e68104eae30cc2370bbd6e1fd011e671a301

The contract's var "creator" returns me the address 41399344aff5722ae2dec4c045c5ed06fc223be33e. I don't know what this address is. I provided private key for the address TFDdwNhPcHQHNq9UE8qQt8YTfeeMRV6yxG

**Comment by sullof** [comment]
That is the base58 version of your address. Try yourself: 
```
tronWeb.address.toHex('TFDdwNhPcHQHNq9UE8qQt8YTfeeMRV6yxG')
> 41399344aff5722ae2dec4c045c5ed06fc223be33e
```

**Comment by guoxbin** [comment]
My case is the same. When I updated the privateKey field in tronbox.js file and deploy contract again, the deployer address did not change
