### ISSUE TITLE
Compile command error

### ISSUE THREAD

**Issue by fellahst** [tronprotocol/tron-box#67]
I am trying to follow the tutorial to run a DApp on the TRON test network using https://medium.com/tron-foundation/how-to-build-a-tron-dapp-5d377cd12061

 I  followed the instruction of the tutorial installed the tronbox tool using npm and clone.
When I execute tronbox compile command I get the following error:

stephanef@STEPHANE-PC /c/code/TronLink-Demo-Messages (master)
λ tronbox compile
C:\Users\stephanef\AppData\Roaming\nvm\v6.14.4\node_modules\tronbox\build\cli.bundled.js:1903
  tronWrap._getContract = async function (address, callback) {
                                ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

Any clue what it could be?

**Comment by sullof** [comment]
@steelcityrkp
`tronbox init` seems to work fine if you run it in an empty folder.
What do you mean exactly?

**Comment by steelcityrkp** [comment]
@sullof 

I am facing the exact same issue as the Original Poster, when trying to run **tronbox compile** on the tutorial project.  For this reason, I did try to run **tronbox init** in an empty folder to see if that would work, but I ran into the same issue again:
![image](https://user-images.githubusercontent.com/4320305/50466095-8dfe9a80-0969-11e9-9151-c256de51e6af.png)

Just thinking out loud... considering the following:
- Your response that you believe  the bug had been resolved
- I assume you are able to run either command without issue
- I am facing the exact same error when running either compile or init
Perhaps, this is is something environmental that is causing this error?

Just for context:
I am running this from Windows PowerShell (all configured and working well with NPM).

Please let me know if there is any other info I could provide that would be helpful, in order to try to isolate and identify what is causing this error.

I don't have access to another machine at the moment, but after some days, I would try to run this from another environment and see if that makes a difference.  It's odd, and it's all within NPM, so it doesn't make sense that surrounding configuration/environment would cause the issue, but just raising this as a possibility... especially if this is working for most people (maybe original poster and myself share some environmental factor that is causing this error...)

Any thoughts or suggestions are appreciated...!  thanks.

**Comment by steelcityrkp** [comment]
I just realized something....!

I didn't have the exact same error as original poster, but I did have a similar error when trying to run **tronbox compile** on the Tutorial/Demo project.

However, as per my last post, I did run into the exact same issue when I tried to run **tronbox init** on an empty folder. 
This is the compile error (the same), for reference:
![image](https://user-images.githubusercontent.com/4320305/50466462-b8515780-096b-11e9-948c-a6191efa0297.png)

**Comment by sullof** [comment]
@steelcityrkp 
Probably you are using an old (unsupported) version of Node. 
I suggest that you install at least Node 8/Carbon. The best way to do it is using nvm:
https://github.com/creationix/nvm/
Let me know if that works.

**Comment by steelcityrkp** [comment]
@sullof 
Really appreciate the guidance...!
Installing and using the latest version of Node did resolve the issue for me, and I was able to successfully compile the contracts! (Additionally, I was able to use **init** and **migrate** successfully as well)

I'm not around my primary development environment at the moment, and the machine I'm using was operating with an older version of Node.

In case it's helpful for reference (I ran into these errors, but everything still worked):
![midsuscce](https://user-images.githubusercontent.com/4320305/50472608-746c4b80-0987-11e9-9432-0b8e858c4a4a.PNG)

I think it's also environmental, and I don't want to add too much here, as it gets outside the scope of this particular issue, but just in case anyone else facing this runs across this and is using Windows, a few notes:
- nvm doesn't run on Windows, but nvm-windows worked well for my setup (https://github.com/coreybutler/nvm-windows)
- I recommend turning on the Linux Subsystem feature in Windows as it enabled bash (https://docs.microsoft.com/en-us/windows/wsl/install-win10)

**Comment by sullof** [comment]
Thanks for that. I will tell the documentation team to take a look.
About the error, that is probably related to the version of node you are using.
